CREATE TABLE CAMPUS(
  COD_CAMPUS INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  NOME VARCHAR(250) NOT NULL,
  QTD_ALUNOS INT NOT NULL,
  DESC_CAMPUS VARCHAR(500))

CREATE TABLE CURSO(
  COD_CURSO INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  CARGA_HORA INT NOT NULL,
  CARGA_ESTAGIO INT NOT NULL,
  NOME_CURSO VARCHAR(45) NOT NULL,
  COD_CAMPUS INT NOT NULL,
  FOREIGN KEY(COD_CAMPUS) REFERENCES USER(COD_CAMPUS)
  ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE DISCIPLINA(
  COD_DISCIPLINA INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  DESC_DISCIPLINA VARCHAR(350) NOT NULL
  CARGA_DISCIPLINA INT NOT NULL
  BIBLIOGRAFIA_DISCI VARCHAR(700) NOT NULL
  NOME_DISCIPLINA VARCHAR(150) NOT NULL
  EMENTA_DISCIPLINA VARCHAR(700) NOT NULL);

VINCULO(
  COD_DISCIPLINA INT NOT NULL;
  COD_CURSO INT NOT NULL;
  FOREIGN KEY(COD_DISCIPLINA) REFERENCES DISCIPLINA(COD_DISCIPLINA)
  ON DELETE NO ACTION ON UPDATE NO ACTION
  FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO)
  ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE ALUNO(
  COD_ALUNO INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  DT_ENCERRAMENTO DATE NOT NULL,
  NOME_ALUNO VARCHAR(250) NOT NULL,
  ENDERECO_ALUNO VARCHAR(350) NOT NULL,
  FONE_ALUNO VARCHAR(14) NOT NULL,
  EMAIL_ALUNO VARCHAR(150) NOT NULL);

CREATE TABLE MATRICULAS(
  COD_MATRICULA INT PRIMARY KEY AUTOINCREMENT,
  DATA_INICIAL DATE NOT NULL
  DATA_PREV_TER DATE NOT NULL
  COD_CURSO INT NOT NULL
  COD_ALUNO INT NOT NULL
  FOREIGN KEY(COD_CURSO) REFERENCES CURSO(COD_CURSO)
  ON DELETE NO ACTION ON UPDATE NO ACTION);
