CREATE TABLE NOMETABELA(
  NOMEATRIBUTO  TIPO  COMPLEMENTO  RESTRIÇÃO,
)

CREATE TABLE USER(
  COD_USER INT PRIMARY KEY AUTOINCREMENT,
  EMAIL VARCHAR(120) UNIQUE NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  DAT_NASC DATE NOT NULL);

CREATE TABLE VENDA(
  COD_VENDA INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  DATA_VENDA TIMESTAMP NOT NULL,
  DATA_ENTREGA TIMESTAMP NOT NULL,
  TRANSP VARCHAR(120) NOT NULL
  LOCAL_ENTREGA VARCHAR(250) NOT NULL
  COD_USER INT NOT NULL,
  FOREIGN KEY(COD_USER) REFERENCES USER(COD_USER)
  ON DELETE NO ACTION ON UPDATE NO ACTION);

ITEM_PED(
  COD_PRODUTO INT NOT NULL,
  COD_VENDA INT NOT NULL,
  QTD_ITEM INT NOT NULL,
  FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
  ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY(COD_VENDA) REFERENCES VENDA(COD_VENDA)
  ON DELETE NO ACTION ON UPDATE NO ACTION);

